version: '3.8'

services:
  redis:
    image: redis:7-alpine
    # Don't expose Redis port externally for security
    # API container can still access it via internal network
    restart: unless-stopped
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Standard API port
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379
      - ENVIRONMENT=production
      - DEBUG=false
    depends_on:
      redis:
        condition: service_started
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 2
    restart: unless-stopped
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 60s

networks:
  app_network:
    driver: bridge