name: CI - Lint and Build Check

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black
    
    - name: Lint with flake8
      run: |
        # Stop the build if there are Python syntax errors or undefined names
        flake8 app --count --select=E9,F63,F7,F82 --show-source --statistics
        # Exit-zero treats all errors as warnings (max complexity 10, line length 127)
        flake8 app --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Format check with black
      run: |
        black --check app || echo "⚠️ Code formatting issues found (non-blocking)"
    
    - name: Build Docker image
      run: |
        mkdir -p scripts  # Ensure scripts directory exists
        docker build -t skinsense-backend:test .
        echo "✅ Docker build successful"
    
    - name: Success
      run: |
        echo "✅ CI checks passed!"
        echo "- Syntax check: ✓"
        echo "- Linting: ✓"
        echo "- Docker build: ✓"